import type { PageDefinition } from './data';

export const newKeywordStylePages: PageDefinition[] = [
  {
    slug: 'instagram-font-generator',
    title: 'Instagram Font Generator',
    metaTitle: 'Instagram Font Generator — Copy & Paste',
    metaDescription: 'Create stylish Unicode fonts for Instagram bios, captions, names, and comments. Preview bold, cursive, aesthetic, and small text, then copy it free.',
    category: 'styles',
    description: 'Create copy-and-paste text styles for Instagram bios, captions, display names, and comments using Unicode characters.',
    content: 'Instagram does not include a general font picker for bios or captions, but many Unicode letters have bold, italic, script, circled, small-cap, and fullwidth forms. Because those forms are characters rather than app formatting, they can be copied into many Instagram text fields and retain their visual style. This generator puts the most useful profile-friendly options together so you can compare one line before pasting it.\n\nUse decorative text selectively. A script display name or bold first line can create contrast, while an entire caption in altered characters is harder to scan and may be announced poorly by screen readers. Important details such as contact information, prices, dates, hashtags, and calls to action are safer in ordinary text.\n\nInstagram may filter particular symbols, count styled characters differently, or change field rules over time. Always preview the final result in the exact bio, caption, comment, or name field before saving it.',
    howToUse: 'Enter a name, short bio line, or caption hook. Compare readable bold, script, small-cap, and aesthetic options, copy one result, and test it in the intended Instagram field.',
    examples: [
      { before: 'Creative Studio', after: '𝗖𝗿𝗲𝗮𝘁𝗶𝘃𝗲 𝗦𝘁𝘂𝗱𝗶𝗼', note: 'Bold profile heading' },
      { before: 'made with care', after: '𝓶𝓪𝓭𝓮 𝔀𝓲𝓽𝓱 𝓬𝓪𝓻𝓮', note: 'Script bio line' },
      { before: 'New post', after: 'ɴᴇᴡ ᴘᴏsᴛ', note: 'Compact small caps' },
      { before: 'Daily notes', after: '✦ 𝒟𝒶𝒾𝓁𝓎 𝓃ℴ𝓉ℯ𝓈 ✦', note: 'Decorative caption accent' },
    ],
    faq: [
      { q: 'Can I paste these fonts into an Instagram bio?', a: 'Many core Unicode styles can be pasted into Instagram bios and display names. Support can vary by character, app version, device, and field, so preview the result before saving.' },
      { q: 'Are these actual Instagram fonts?', a: 'No. The tool substitutes Unicode characters that look styled; it does not change Instagram\'s interface font or install a typeface.' },
      { q: 'Which style is easiest to read?', a: 'Bold, italic, and small caps are usually easier to scan than heavily decorated, inverted, or glitch text. Keep essential profile information in regular characters.' },
    ],
    relatedSlugs: ['tiktok-font-generator', 'aesthetic-font-generator', 'cursive-font-generator'],
    icon: '📸',
    defaultStyleIds: ['sansBold', 'boldScript', 'smallCaps', 'sparkle'],
  },
  {
    slug: 'tattoo-font-generator',
    title: 'Tattoo Font Generator',
    metaTitle: 'Tattoo Font Generator — Lettering Ideas',
    metaDescription: 'Preview names, dates, and short tattoo lettering in script, gothic, Old English, and bold styles. Free idea generator for artist discussions.',
    category: 'styles',
    description: 'Compare script, gothic, Old English, and bold lettering ideas for names, dates, quotes, and other text-based tattoo concepts.',
    content: 'A tattoo font generator is most useful at the idea stage: it lets you compare the same word in flowing script, dense blackletter, restrained serif, and strong display styles before discussing the design with an artist. Short names, dates, initials, and compact phrases reveal differences in letter shape more clearly than long paragraphs.\n\nThe output on this page is copyable Unicode, not an ink-ready stencil or a downloadable typeface. Unicode can suggest a direction, but it cannot account for body placement, skin movement, line spread, negative space, or how small details may age. Bring several readable references to a qualified tattoo artist and let them redraw the final lettering for the chosen placement.\n\nCheck spelling, capitalization, dates, and translations independently before committing to permanent artwork. A generator is a comparison tool, not a substitute for professional design and safety advice.',
    howToUse: 'Type the exact word, name, or date you are considering. Compare script, fraktur, bold, and minimal options, then save the plain spelling and a few styled references for your artist.',
    examples: [
      { before: 'Always', after: '𝓐𝓵𝔀𝓪𝔂𝓼', note: 'Bold script idea' },
      { before: 'Family', after: '𝔉𝔞𝔪𝔦𝔩𝔶', note: 'Old English direction' },
      { before: 'Memento Mori', after: '𝕸𝖊𝖒𝖊𝖓𝖙𝖔 𝕸𝖔𝖗𝖎', note: 'Bold gothic concept' },
      { before: '1998', after: '𝟏𝟗𝟗𝟖', note: 'Clean bold numerals' },
    ],
    faq: [
      { q: 'Can I use this output as a tattoo stencil?', a: 'No. It is a Unicode lettering preview. Ask a tattoo artist to create or approve the final stencil for the exact size and placement.' },
      { q: 'Which tattoo lettering style ages best?', a: 'There is no universal answer. Size, stroke width, spacing, placement, skin, and aftercare all matter. A qualified artist can judge whether the design has enough open space and line weight.' },
      { q: 'Should I verify names, dates, and foreign-language text?', a: 'Yes. Check the source spelling and meaning separately and show the plain-text version to your artist. Do not rely on decorative characters as the only reference.' },
    ],
    relatedSlugs: ['cursive-tattoo-font-generator', 'chicano-font-generator', 'fraktur-font-generator'],
    icon: '🖋️',
    defaultStyleIds: ['boldScript', 'boldFraktur', 'script', 'bold'],
    disclaimer: 'This generator provides visual lettering ideas only. It does not create a tattoo stencil or replace consultation with a qualified tattoo artist.',
  },
  {
    slug: 'name-font-generator',
    title: 'Name Font Generator',
    metaTitle: 'Name Font Generator — Stylish Names',
    metaDescription: 'Turn your name into stylish copy-and-paste text. Compare cursive, bold, gothic, aesthetic, and gaming name fonts free in your browser.',
    category: 'styles',
    description: 'Preview your name in cursive, bold, gothic, clean, and decorative Unicode styles for profiles, messages, and creative ideas.',
    content: 'Names are short, personal, and seen repeatedly, so small typographic differences matter. This generator shows the same name across flowing script, bold sans, small caps, fraktur, circled, and decorative styles. The results are copyable Unicode characters suited to display names, bios, contacts, invitations, and early wordmark exploration.\n\nChoose the style for the destination. A clean bold or small-cap name remains readable in compact profile layouts; script feels personal or signature-like; fraktur and symbol frames suit darker or gaming aesthetics. If a service restricts special characters in account usernames, try the styled result in its display-name field instead.\n\nThis tool styles a name you provide; it does not invent identities, check username availability, or create a licensed logo font. For branding, keep a plain-text version and use a real typeface with appropriate licensing in the final artwork.',
    howToUse: 'Enter your first name, full name, nickname, or initials. Compare styles at a glance, copy your favorite, and test it in the profile or project where it will appear.',
    examples: [
      { before: 'Alex Morgan', after: '𝓐𝓵𝓮𝔁 𝓜𝓸𝓻𝓰𝓪𝓷', note: 'Signature-like script' },
      { before: 'NOVA', after: 'ɴᴏᴠᴀ', note: 'Compact small caps' },
      { before: 'Raven', after: '𝕽𝖆𝖛𝖊𝖓', note: 'Bold gothic name' },
      { before: 'Mia', after: '♡ 𝑀𝒾𝒶 ♡', note: 'Soft framed name' },
    ],
    faq: [
      { q: 'Can I use a styled name as a username?', a: 'Some services accept Unicode only in display names, while usernames or handles may be limited to letters, numbers, periods, and underscores. Test the exact field.' },
      { q: 'Does this generator check whether a name is available?', a: 'No. It only changes the visual characters. Username, domain, and trademark availability must be checked separately.' },
      { q: 'Why do some letters stay unchanged?', a: 'Not every Unicode style contains every accented letter, digit, or symbol. Unsupported characters remain in their original form so the name stays recognizable.' },
    ],
    relatedSlugs: ['cursive-font-generator', 'instagram-font-generator', 'aesthetic-font-generator'],
    icon: '👤',
    defaultStyleIds: ['boldScript', 'sansBold', 'smallCaps', 'fraktur'],
  },
  {
    slug: 'aesthetic-font-generator',
    title: 'Aesthetic Font Generator',
    metaTitle: 'Aesthetic Font Generator — Copy & Paste',
    metaDescription: 'Generate aesthetic Unicode text for bios, captions, usernames, and mood boards. Try soft script, spaced, fullwidth, sparkle, and gothic styles.',
    category: 'styles',
    description: 'Build soft, minimal, dreamy, retro, or dark aesthetic text with script letters, spacing, symbols, and Unicode style combinations.',
    content: '“Aesthetic” is an umbrella intent rather than one typeface. Soft profiles often use light script and heart accents; minimal layouts rely on small caps and generous spacing; vaporwave and Y2K designs use fullwidth or monospace characters; dark-academia looks lean toward serif and fraktur. This generator groups those directions so you can compare the mood of the same phrase.\n\nA strong aesthetic usually comes from restraint and repetition. Choose one primary letter style and one symbol family, then reuse them consistently across a bio, highlight label, or short caption. Mixing every decorative alphabet at once makes the output look random and reduces readability.\n\nThese results are Unicode text, so spacing and symbols can render differently between devices. Use them for short visual accents, and keep essential names, links, dates, and instructions available in plain text.',
    howToUse: 'Enter a short phrase or profile line. Compare soft script, minimal spacing, retro fullwidth, and darker fraktur options, then copy the style that matches your visual theme.',
    examples: [
      { before: 'soft mornings', after: '✦ 𝓈ℴ𝒻𝓉 𝓂ℴ𝓇𝓃𝒾𝓃ℊ𝓈 ✦', note: 'Soft script aesthetic' },
      { before: 'less is more', after: 'ʟ ᴇ s s · ɪ s · ᴍ ᴏ ʀ ᴇ', note: 'Minimal spaced style' },
      { before: 'digital dreams', after: 'ｄｉｇｉｔａｌ ｄｒｅａｍｓ', note: 'Vaporwave fullwidth' },
      { before: 'dark library', after: '𝔡𝔞𝔯𝔨 𝔩𝔦𝔟𝔯𝔞𝔯𝔶', note: 'Dark-academia direction' },
    ],
    faq: [
      { q: 'What makes text aesthetic?', a: 'The effect comes from a consistent combination of letter shape, spacing, capitalization, and restrained symbols that supports a particular mood.' },
      { q: 'Which aesthetic style works best for a bio?', a: 'Short script, small caps, or lightly spaced text tends to fit narrow mobile layouts. Preview the full bio to check wrapping.' },
      { q: 'Can I combine multiple outputs?', a: 'Yes, but one main style plus a small accent is usually more coherent and readable than mixing many unrelated alphabets.' },
    ],
    relatedSlugs: ['instagram-font-generator', 'y2k-font-generator', 'glitter-font-generator'],
    icon: '✨',
    defaultStyleIds: ['sparkle', 'script', 'spaced', 'fullwidth'],
  },
  {
    slug: 'creepy-scary-font-generator',
    title: 'Creepy & Scary Font Generator',
    metaTitle: 'Creepy & Scary Font Generator — Horror Text',
    metaDescription: 'Create creepy and scary Unicode text for Halloween, horror stories, gaming names, and spooky posts. Copy gothic, glitch, and corrupted styles free.',
    category: 'styles',
    description: 'Turn ordinary words into creepy, scary, and unsettling Unicode text with gothic letters, crosses, scratches, and controlled glitch effects.',
    content: 'Creepy and scary font searches share the same practical goal: make a short phrase feel unsettling before it is read. The strongest copy-and-paste options combine blackletter shapes, broken strokes, inverted characters, crosses, and controlled combining marks. This page keeps both keyword intents together because the useful output and common destinations overlap heavily.\n\nChoose intensity based on context. Fraktur or crossed text remains readable for a horror title, Halloween invite, or dark gaming name. Glitch and combining-mark effects feel more corrupted, but they can change line height, overlap nearby interface elements, and become difficult for assistive technology.\n\nUse scary styling for atmosphere, not for urgent instructions, dates, addresses, or content warnings. If a platform rejects heavy effects, switch to a simpler gothic style and shorten the phrase.',
    howToUse: 'Type a horror title, spooky username, or Halloween phrase. Start with readable gothic options, then compare glitch, crossed, and inverted styles for a stronger effect.',
    examples: [
      { before: 'Do Not Enter', after: '𝕯𝖔 𝕹𝖔𝖙 𝕰𝖓𝖙𝖊𝖗', note: 'Readable scary blackletter' },
      { before: 'Haunted', after: '† 𝕳𝖆𝖚𝖓𝖙𝖊𝖉 †', note: 'Gothic frame' },
      { before: 'Signal Lost', after: 'S̶̈í̷g̶̈ń̷ä̶ĺ̷ L̶̈ó̷s̶̈t̷́', note: 'Controlled glitch' },
      { before: 'Behind You', after: 'uoY dniheB', note: 'Backwards effect' },
    ],
    faq: [
      { q: 'Why are creepy and scary combined on one page?', a: 'Their search results and use cases overlap: both commonly seek horror, Halloween, gothic, corrupted, and unsettling text styles. One focused tool avoids near-duplicate pages.' },
      { q: 'Is creepy text the same as Zalgo text?', a: 'Zalgo is one heavy combining-mark technique. Creepy text is broader and can include readable fraktur, crossed letters, inverted text, and lighter glitch effects.' },
      { q: 'Why can glitch text break line spacing?', a: 'Combining marks stack above and below base letters. Some apps reserve extra height for them or clip them differently.' },
    ],
    relatedSlugs: ['horror-font-generator', 'glitch-font-generator', 'goth-font-generator'],
    icon: '👻',
    defaultStyleIds: ['boldFraktur', 'gothicFrame', 'glitch', 'cross'],
  },
  {
    slug: 'goth-font-generator',
    title: 'Goth Font Generator',
    metaTitle: 'Goth Font Generator — Dark Gothic Text',
    metaDescription: 'Generate dark goth text with blackletter, crosses, bold fraktur, and dramatic Unicode styles. Copy and paste names, bios, and captions free.',
    category: 'styles',
    description: 'Create dark, romantic, and dramatic goth text using blackletter alphabets, ornamental crosses, strong italics, and restrained symbols.',
    content: 'Goth typography is broader than a single medieval alphabet. Traditional blackletter supplies dense broken strokes, while romantic goth styling can use elegant script, sharp italics, crosses, and carefully spaced capitals. This generator emphasizes the darker visual language used in alternative profiles, music communities, event titles, and fashion captions.\n\nFor readable goth text, start with regular or bold fraktur and keep the phrase short. Cross frames and overlines add atmosphere without replacing the letters themselves. Glitch belongs more to industrial or cyber-goth directions and works best as an occasional accent.\n\nUnicode approximates these moods but cannot reproduce a custom band logo, professionally drawn blackletter, or a licensed typeface. Use the output for copy-paste display text and early style exploration; use real fonts or custom lettering for final print and branding work.',
    howToUse: 'Enter a name, lyric-length phrase, or event title. Compare classic fraktur, bold blackletter, cross-framed, and dramatic italic results, then test the copied text at its final size.',
    examples: [
      { before: 'Midnight', after: '𝔐𝔦𝔡𝔫𝔦𝔤𝔥𝔱', note: 'Classic blackletter' },
      { before: 'Nocturne', after: '𝕹𝖔𝖈𝖙𝖚𝖗𝖓𝖊', note: 'Bold fraktur' },
      { before: 'Dark Romance', after: '† 𝕯𝖆𝖗𝖐 𝕽𝖔𝖒𝖆𝖓𝖈𝖊 †', note: 'Cross-framed goth' },
      { before: 'After Dark', after: '𝑨𝒇𝒕𝒆𝒓 𝑫𝒂𝒓𝒌', note: 'Dramatic serif italic' },
    ],
    faq: [
      { q: 'What is the difference between goth and gothic text?', a: 'They overlap, but goth can refer to a modern alternative subculture and its romantic, punk, or industrial variants, while gothic typography often points specifically to blackletter traditions.' },
      { q: 'Does goth text work in social profiles?', a: 'Many Unicode blackletter characters work in display-name and bio fields, but platform filters and device rendering vary. Test a short result first.' },
      { q: 'Is this an Old English font file?', a: 'No. It produces Unicode fraktur and decorative characters for copy and paste; it does not install or distribute a typeface.' },
    ],
    relatedSlugs: ['fraktur-font-generator', 'creepy-scary-font-generator', 'metal-font-generator'],
    icon: '🦇',
    defaultStyleIds: ['fraktur', 'boldFraktur', 'gothicFrame', 'boldItalic'],
  },
  {
    slug: 'medieval-font-generator',
    title: 'Medieval Font Generator',
    metaTitle: 'Medieval Font Generator — Castle & Fantasy Text',
    metaDescription: 'Create medieval-style Unicode text for fantasy names, castle events, roleplay, and game profiles. Copy fraktur, manuscript, and heraldic styles.',
    category: 'styles',
    description: 'Generate castle, manuscript, heraldic, and fantasy-inspired text with fraktur, bold blackletter, serif, and ornamental Unicode styles.',
    content: 'Medieval-themed text usually blends several historical and fantasy signals: blackletter forms associated with later European manuscripts, formal serif capitals, heraldic symbols, and generous spacing. This generator offers Unicode approximations for roleplay names, castle-event headings, fantasy guild labels, and themed social posts.\n\n“Medieval” covers many centuries and writing traditions, so no single output is historically universal. Fraktur itself developed after much of the medieval period, even though modern audiences strongly associate its broken strokes with old manuscripts and fantasy worlds. Treat the styles here as readable medieval-inspired shorthand rather than scholarly reproductions.\n\nFor invitations or event material, reserve ornate text for the title and keep dates, locations, accessibility details, and ticket links in plain characters. For historically accurate design, consult manuscript references and use an appropriately licensed typeface.',
    howToUse: 'Enter a castle name, guild title, character name, or short announcement. Compare regular and bold fraktur with formal serif and ornamental frames.',
    examples: [
      { before: 'The Old Keep', after: '𝔗𝔥𝔢 𝔒𝔩𝔡 𝔎𝔢𝔢𝔭', note: 'Manuscript-inspired fraktur' },
      { before: 'Knights Hall', after: '𝕶𝖓𝖎𝖌𝖍𝖙𝖘 𝕳𝖆𝖑𝖑', note: 'Bold fantasy blackletter' },
      { before: 'Royal Feast', after: '★ 𝐑𝐨𝐲𝐚𝐥 𝐅𝐞𝐚𝐬𝐭 ★', note: 'Heraldic display style' },
      { before: 'Guild of Dawn', after: '𝔊𝔲𝔦𝔩𝔡 𝔬𝔣 𝔇𝔞𝔴𝔫', note: 'Fantasy guild name' },
    ],
    faq: [
      { q: 'Is fraktur truly medieval?', a: 'Fraktur developed in the early modern period, after the conventional end of the Middle Ages. It is included because contemporary fantasy design strongly associates blackletter with medieval settings.' },
      { q: 'Can I use this for a fantasy game name?', a: 'Yes, if the game accepts the selected Unicode characters. Some games restrict names to basic letters, so test before committing.' },
      { q: 'Is the output historically accurate calligraphy?', a: 'No. It is a Unicode-based visual approximation. Historical projects should use primary references and a suitable licensed typeface or calligrapher.' },
    ],
    relatedSlugs: ['fraktur-font-generator', 'western-font-generator', 'goth-font-generator'],
    icon: '🏰',
    defaultStyleIds: ['fraktur', 'boldFraktur', 'gothicFrame', 'bold'],
  },
  {
    slug: 'metal-font-generator',
    title: 'Metal Font Generator',
    metaTitle: 'Metal Font Generator — Heavy & Gothic Text',
    metaDescription: 'Create heavy metal-inspired Unicode text with bold blackletter, sharp strokes, crosses, and glitch effects for names, bios, and music posts.',
    category: 'styles',
    description: 'Generate heavy, black, death, doom, and industrial metal-inspired copy-paste text using bold blackletter and aggressive Unicode effects.',
    content: 'Metal lettering ranges from readable heavy serif titles to almost illegible black-metal logos. Unicode cannot draw custom thorn-like ligatures or mirrored band marks, but bold fraktur, slash overlays, crosses, dark enclosures, and glitch effects can give short copy-paste text a heavy, aggressive direction.\n\nMatch the treatment to the subgenre and use case. Bold blackletter suits classic and doom-metal moods; sharper slashed text feels more extreme; monospace and glitch effects lean industrial. For a social bio or playlist title, preserve enough letter structure that the name remains recognizable.\n\nThis is a generic metal-style tool, distinct from the existing Metallica-inspired page. It does not reproduce any band logo. For album art, merchandise, or a commercial identity, commission original lettering or use a properly licensed metal typeface.',
    howToUse: 'Type a band-style name, playlist title, or short phrase. Compare bold blackletter, slashed, crossed, and industrial glitch options, then copy the most readable match.',
    examples: [
      { before: 'Iron Ritual', after: '𝕴𝖗𝖔𝖓 𝕽𝖎𝖙𝖚𝖆𝖑', note: 'Heavy blackletter' },
      { before: 'Doom Engine', after: '† 𝕯𝖔𝖔𝖒 𝕰𝖓𝖌𝖎𝖓𝖊 †', note: 'Doom-metal frame' },
      { before: 'Noise', after: 'N̸o̸i̸s̸e̸', note: 'Slashed extreme style' },
      { before: 'Machine Cult', after: '〈𝙼𝚊𝚌𝚑𝚒𝚗𝚎 𝙲𝚞𝚕𝚝〉', note: 'Industrial direction' },
    ],
    faq: [
      { q: 'Can this recreate a black-metal band logo?', a: 'No. Complex band logos depend on custom drawing, ligatures, texture, and composition that plain Unicode cannot reproduce.' },
      { q: 'How is this different from the Metallica font page?', a: 'This page targets the broad metal genre and multiple subgenre moods. The Metallica page is a separate unofficial brand-specific intent.' },
      { q: 'Can I use the output for a commercial logo?', a: 'Unicode characters themselves are copyable, but a final commercial identity needs originality, legibility checks, and trademark review. Custom lettering is the safer professional route.' },
    ],
    relatedSlugs: ['metallica-font-generator', 'goth-font-generator', 'glitch-font-generator'],
    icon: '🤘',
    defaultStyleIds: ['boldFraktur', 'gothicFrame', 'slash', 'glitch'],
  },
  {
    slug: 'glitch-font-generator',
    title: 'Glitch Font Generator',
    metaTitle: 'Glitch Font Generator — Corrupted Text',
    metaDescription: 'Generate copy-and-paste glitch text for cyberpunk names, gaming profiles, tech posts, and horror effects. Try light distortion and corrupted styles.',
    category: 'styles',
    description: 'Create readable digital distortion, corrupted text, hacker-style labels, and stronger glitch effects with Unicode combining marks.',
    content: 'Glitch text simulates corrupted data and broken displays by layering Unicode combining marks across ordinary letters. Lighter variants use one or two strokes per character and remain recognizable; heavier effects stack more marks, increase line height, and can look like visual noise from a damaged interface.\n\nThe most practical uses are short: cyberpunk usernames, game clan labels, tech-themed headings, fictional error messages, and horror accents. A subtle glitch often communicates the idea more effectively than maximum distortion because readers can still identify the word.\n\nCombining marks are rendered by the destination app and font, so the same output may overlap, clip, or be rejected in some fields. They can also be difficult for screen readers. Keep important information in plain text and switch to monospace, slash, or strikethrough if the stronger effect breaks the layout.',
    howToUse: 'Type a short name or phrase. Compare the light glitch result with slash, strikethrough, monospace, and framed tech alternatives before pasting it.',
    examples: [
      { before: 'SYSTEM ERROR', after: 'S̶̈Ý̷S̶̈T̷́Ë̶Ḿ̷ Ë̶Ŕ̷R̶̈Ó̷R̶̈', note: 'Light corrupted effect' },
      { before: 'Offline', after: 'O̸f̸f̸l̸i̸n̸e̸', note: 'Slashed distortion' },
      { before: 'Data Ghost', after: '〈𝙳𝚊𝚝𝚊 𝙶𝚑𝚘𝚜𝚝〉', note: 'Readable tech frame' },
      { before: 'Signal', after: 'S̶i̶g̶n̶a̶l̶', note: 'Simple strike glitch' },
    ],
    faq: [
      { q: 'How does glitch text work?', a: 'It appends Unicode combining marks to base letters. Fonts position those marks above, through, or around the character to create distortion.' },
      { q: 'Why does glitch text look different after pasting?', a: 'Apps and operating systems use different fallback fonts, clipping rules, filters, and line-height calculations for combining marks.' },
      { q: 'Is lighter glitch text better for usernames?', a: 'Usually. It is easier to read and less likely to be rejected or clipped, though every platform has its own character rules.' },
    ],
    relatedSlugs: ['creepy-scary-font-generator', 'y2k-font-generator', 'weird-text-generator'],
    icon: '📺',
    defaultStyleIds: ['glitch', 'slash', 'strikethrough', 'monospace'],
  },
  {
    slug: 'typewriter-font-generator',
    title: 'Typewriter & Old Font Generator',
    metaTitle: 'Typewriter Font Generator — Old-Style Text',
    metaDescription: 'Create old typewriter-style text with monospace, serif, distressed, and vintage Unicode effects. Copy retro text for bios, captions, and headings.',
    category: 'styles',
    description: 'Generate old typewriter and vintage text with fixed-width letters, serif alternatives, spacing, and restrained worn-document effects.',
    content: 'Typewriter text is defined by fixed-width characters: every letter occupies the same horizontal space because mechanical machines advanced the carriage by a consistent amount. Unicode mathematical monospace characters provide the closest copy-and-paste approximation, while serif, underline, and light strike effects suggest older documents and imperfect ribbon impressions.\n\nThe phrase “old font generator” is broader and can also mean Old English, antique print, or vintage display type. Search results around old typewriter text overlap strongly enough to serve both needs on one page, while dedicated fraktur and retro pages cover the distinct Old English and decade-based directions.\n\nUnicode does not reproduce ink texture, uneven key pressure, paper grain, or a specific machine such as an Underwood or Olivetti. For a realistic poster or image, use a licensed typewriter font and add texture in design software. Use this page when you need text that stays copyable.',
    howToUse: 'Type a note, title, or short quote. Start with monospace for the clearest typewriter effect, then compare serif, spacing, underline, and worn-looking alternatives.',
    examples: [
      { before: 'Case File 27', after: '𝙲𝚊𝚜𝚎 𝙵𝚒𝚕𝚎 𝟸𝟽', note: 'Classic monospace' },
      { before: 'Private Notes', after: 'P r i v a t e   N o t e s', note: 'Spaced archival label' },
      { before: 'Draft Copy', after: 'D̶r̶a̶f̶t̶ C̶o̶p̶y̶', note: 'Corrected draft effect' },
      { before: 'The Old House', after: '𝐓𝐡𝐞 𝐎𝐥𝐝 𝐇𝐨𝐮𝐬𝐞', note: 'Vintage serif direction' },
    ],
    faq: [
      { q: 'Why are typewriter and old font keywords combined?', a: 'The useful copy-paste intent overlaps around monospace and vintage text. Old English and broader retro aesthetics already have more specific related pages.' },
      { q: 'Is monospace the same as a typewriter font?', a: 'Monospace describes equal character widths, a core typewriter trait. Real typewriter faces also have serif shapes, mechanical irregularities, and ink texture that Unicode cannot capture.' },
      { q: 'Can I download a typewriter font here?', a: 'No. This page creates copyable Unicode text. Use a licensed TTF or OTF typeface when you need authentic typesetting or image export.' },
    ],
    relatedSlugs: ['retro-font-generator', 'fraktur-font-generator', 'ransom-note-font-generator'],
    icon: '⌨️',
    defaultStyleIds: ['monospace', 'spaced', 'strikethrough', 'bold'],
  },
  {
    slug: 'japanese-font-generator',
    title: 'Japanese Font Generator',
    metaTitle: 'Japanese Font Generator — Aesthetic Text',
    metaDescription: 'Create Japanese-inspired Unicode text and style existing Japanese characters for bios, names, and captions. Decorative only—not a translation tool.',
    category: 'styles',
    description: 'Create Japanese-inspired aesthetic text with fullwidth letters, clean spacing, brackets, and symbols while preserving Japanese characters you enter.',
    content: 'Japanese font generator searches mix two different needs: styling real Japanese text and giving Latin text a Japanese-inspired visual direction. This copy-paste tool preserves hiragana, katakana, and kanji that you enter, while offering fullwidth Latin letters, clean spacing, brackets, and tech-oriented frames for anime, gaming, vaporwave, and Japan-themed profiles.\n\nIt does not translate English into Japanese, transliterate names into kana, or change the font used to draw kanji. Unicode contains many styled mathematical Latin alphabets, but it does not contain bold, script, or fraktur duplicates for every Japanese character. As a result, actual Japanese characters often remain unchanged while surrounding Latin letters and symbols change.\n\nFor meaningful Japanese words, names, tattoos, or public branding, verify spelling, reading, grammar, and cultural context with a qualified speaker or translator. Avoid replacing Latin letters with unrelated CJK lookalikes, which can produce meaningless or misleading text.',
    howToUse: 'Enter Latin text or Japanese characters you have already verified. Compare fullwidth, spaced, bracketed, and clean Unicode treatments, then copy the result as a decorative accent.',
    examples: [
      { before: 'Tokyo Nights', after: 'Ｔｏｋｙｏ Ｎｉｇｈｔｓ', note: 'Fullwidth Latin style' },
      { before: 'NEO TOKYO', after: '〈𝙽𝙴𝙾 𝚃𝙾𝙺𝚈𝙾〉', note: 'Tech bracket style' },
      { before: '桜', after: '【 桜 】', note: 'Japanese text preserved and framed' },
      { before: '東京 2026', after: '東京 · 𝟸𝟶𝟸𝟼', note: 'Mixed Japanese and styled digits' },
    ],
    faq: [
      { q: 'Does this translate English into Japanese?', a: 'No. It styles text and preserves Japanese characters you enter. Use a qualified translation source for actual Japanese wording.' },
      { q: 'Why do kanji, hiragana, or katakana stay unchanged?', a: 'Unicode does not provide the same decorative mathematical style sets for Japanese scripts that it provides for Latin letters.' },
      { q: 'Can I use the result for a Japanese tattoo?', a: 'Do not rely on this tool for wording. Verify the exact language with a qualified Japanese speaker and have the tattoo artist create the final lettering and stencil.' },
    ],
    relatedSlugs: ['y2k-font-generator', 'aesthetic-font-generator', 'typewriter-font-generator'],
    icon: '🗾',
    defaultStyleIds: ['fullwidth', 'wideSpaced', 'angleBrackets', 'monospace'],
    disclaimer: 'This is a decorative text-style tool, not a Japanese translator or transliterator. Verify meaningful Japanese text independently before publication or permanent use.',
  },
];

export const newKeywordFandomPages: PageDefinition[] = [
  {
    slug: 'minecraft-font-generator',
    title: 'Minecraft Font Generator',
    metaTitle: 'Minecraft Font Generator — Blocky Game Text',
    metaDescription: 'Create unofficial Minecraft-inspired blocky Unicode text for server names, signs, profiles, and fan posts. Copy pixel-style alternatives free.',
    category: 'fandom',
    description: 'Create unofficial blocky, pixel-inspired Unicode text for Minecraft server names, Discord roles, signs, and fan content.',
    content: 'Minecraft font searches usually seek chunky pixel lettering for a server, thumbnail, sign, or fan project. The official game logo is custom dimensional artwork, while in-game text uses pixel-oriented fonts. Plain Unicode cannot reproduce either exactly, but squared capitals, monospace letters, fullwidth text, and block frames can suggest a game-interface direction while remaining copyable.\n\nThis broader Minecraft page is separate from the existing Minecraftia page. Minecraftia refers to a specific community typeface recreation; this page serves the wider intent around blocky fan text, server labels, profile names, and copy-paste alternatives.\n\nFor a true logo or texture-pack asset, use properly licensed design resources and export an image. The output here is best for short fan-facing text in fields that accept Unicode. Some Minecraft editions, servers, plugins, and consoles restrict characters, so test the result before relying on it.',
    howToUse: 'Type a server name, realm label, role, or fan message. Compare squared, pixel-framed, monospace, and fullwidth variants, then test the copied result in the exact destination.',
    examples: [
      { before: 'Creeper Club', after: '🄲🅁🄴🄴🄿🄴🅁 🄲🄻🅄🄱', note: 'Squared game text' },
      { before: 'Diamond Realm', after: '▣ 🄳🄸🄰🄼🄾🄽🄳 🅁🄴🄰🄻🄼 ▣', note: 'Pixel frame' },
      { before: 'Redstone Lab', after: '𝚁𝚎𝚍𝚜𝚝𝚘𝚗𝚎 𝙻𝚊𝚋', note: 'Monospace interface style' },
      { before: 'Build Together', after: 'Ｂｕｉｌｄ Ｔｏｇｅｔｈｅｒ', note: 'Wide blocky alternative' },
    ],
    faq: [
      { q: 'Does this generate the official Minecraft logo?', a: 'No. The official logo is custom artwork with dimensional stone effects. This tool creates unofficial Unicode alternatives.' },
      { q: 'How is this different from the Minecraftia page?', a: 'Minecraftia is a specific community typeface intent. This page targets the broader search for Minecraft-inspired block, pixel, server, and fan text.' },
      { q: 'Will the text work inside Minecraft?', a: 'Support depends on edition, server configuration, plugins, and the exact field. Some characters may be blocked or rendered as missing glyphs, so test first.' },
    ],
    relatedSlugs: ['minecraftia-font-generator', 'mario-font-generator', 'glitch-font-generator'],
    icon: '⛏️',
    defaultStyleIds: ['squared', 'pixelFrame', 'monospace', 'fullwidth'],
    disclaimer: 'This is an unofficial fan-made tool. Minecraft is a trademark of Mojang Synergies AB. This site is not affiliated with, endorsed by, or sponsored by Mojang or Microsoft.',
  },
  {
    slug: 'fortnite-font-generator',
    title: 'Fortnite Font Generator',
    metaTitle: 'Fortnite Font Generator — Unofficial Game Text',
    metaDescription: 'Create unofficial Fortnite-inspired bold Unicode text for squad names, profiles, party posts, and fan content. Free copy-and-paste alternatives.',
    category: 'fandom',
    description: 'Generate unofficial bold, condensed-feeling, game-style Unicode text for Fortnite squad names, profiles, party messages, and fan posts.',
    content: 'Fortnite font searches often seek the bold, compact energy of the game\'s promotional headings for thumbnails, party invitations, squad labels, and player profiles. The official wordmark uses custom design treatment, and Unicode cannot reproduce its condensed proportions or logo composition exactly. Heavy sans, squared capitals, wide display characters, and strong frames provide practical copy-paste alternatives.\n\nKeep player names recognizable. A bold sans result works better for a squad list or profile, while squared and framed options can carry more of an arcade or battle-interface mood in short headings. If a game account field refuses the characters, use the result in Discord, a stream description, or a social post instead.\n\nThis independent fan tool does not provide the Fortnite logo or game assets. For thumbnails, merchandise, or commercial artwork, use original design work and confirm all relevant brand and asset permissions.',
    howToUse: 'Enter a squad name, player label, or party message. Compare bold sans, squared, dark-circled, and game-frame outputs, then test your favorite where it will be used.',
    examples: [
      { before: 'Victory Squad', after: '𝗩𝗶𝗰𝘁𝗼𝗿𝘆 𝗦𝗾𝘂𝗮𝗱', note: 'Bold game heading' },
      { before: 'Drop Zone', after: '🄳🅁🄾🄿 🅉🄾🄽🄴', note: 'Squared capitals' },
      { before: 'Ready Up', after: '➜ 𝗥𝗲𝗮𝗱𝘆 𝗨𝗽 ←', note: 'Action frame' },
      { before: 'Battle Night', after: 'Ｂａｔｔｌｅ Ｎｉｇｈｔ', note: 'Wide display style' },
    ],
    faq: [
      { q: 'Is this the official Fortnite font?', a: 'No. It creates Unicode styles with a bold game-like feel and does not reproduce or distribute the official wordmark or font assets.' },
      { q: 'Can I use these characters in my Fortnite display name?', a: 'Epic account naming rules and supported characters can change. Test the exact output; if it is rejected, keep an ASCII version for the account name.' },
      { q: 'Can I use the output for fan content?', a: 'It can be used as decorative text for ordinary fan posts, but avoid implying official endorsement and do not treat it as licensed brand artwork.' },
    ],
    relatedSlugs: ['minecraft-font-generator', 'mario-font-generator', 'big-font-generator'],
    icon: '🪂',
    defaultStyleIds: ['sansBold', 'squared', 'darkCircled', 'arrows'],
    disclaimer: 'This is an unofficial fan-made tool. Fortnite is a trademark of Epic Games, Inc. This site is not affiliated with, endorsed by, or sponsored by Epic Games.',
  },
];
